### ISSUE TITLE
Week 10 - Final Exam (Individual - Final MCQ Test and Corrections)

### ISSUE THREAD

**Issue by rohitd3** [aaditgupta21/silverscreen#61]
5.1 to 5.6 Journal Video Notes and Quizzes  - 1 pt

Individual - Final MCQ Test - Friday 2/18 at 8:00am

AP MCQ Test and Corrections (3 pts)

**Comment by rohitd3** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/44128572/154140868-f8c6735f-8bc9-46bd-8f8d-0e3c0b9e3acb.png">

**Comment by aaditgupta21** [comment]
![image](https://user-images.githubusercontent.com/50186752/154633844-25f82916-5bdf-45ee-a468-a9b25f71f745.png)

**Comment by somaditya1** [comment]
![image](https://user-images.githubusercontent.com/89167149/154634102-d5764699-6325-46eb-8563-dbc180932085.png)
Q16: I put c, the correct answer would B because individuals can freely distribute with a creative commons.  
Q23: The correct answer is the internet counties to scale up
Q24: Here, I made a silly error and have no idea what I was thinking at the time. C is the most basic yet correct example of the compression 
Q25 :The procedure does not take place as I had previously thought, it simply returns to n
Q44: The mistake I made here was that I did not have overflow errors, the correct answer was B 
Q50: This mistake I made here was that I did not know that the encryption was public
Q61: The answer refers to a broader term, so C
Q63 The problem here was that I had a or rather than an and so A,D

**Comment by JasonO12** [comment]
![image](https://user-images.githubusercontent.com/89180255/154634184-ae9e6ca3-d500-46c6-9916-5fb35314dd8c.png)

**Comment by jacksongolding** [comment]
![image](https://user-images.githubusercontent.com/89219498/154635650-2e233a73-c519-409d-bca3-12d28d827c47.png)
Corrections:
9. I said A, but the answer is B because digital audio is represented with bits, not inputs.
12. I said A, but the answer is C because A would not continue moving the robot after turning and moving once, while C would.
19. I said B, but the answer is D because password strength does not affect keylogging.
44. I said A, but the answer is B because round-off errors lead to imprecise values, not overflow errors.
49. I said C, but the answer is D because some algorithms are too complicated for computers to solve.
50. I said C, but the answer is A because symmetric encryption uses one key encryption and decryption.
